<template>
  <div class="box">
    <div id="wrapper">
      <h2 @click="ck">点我</h2>
      <div id="scroller">
        <!-- <gourd-title v-for="postItem in posts" :key="postItem.postID" :title="postItem.title" :covers="postItem.images" :author="postItem.user.nick" see="98878" info="89553" time="10分钟前">
          <template slot="title-prefix">
            <gourd-tag type="success">新</gourd-tag>
          </template>
        </gourd-title> -->

      </div>

      <div>是我</div>

      {{$data.$scroller.innerText}}
    </div>
  </div>

</template>

<script>
export default {
	data() {
		return {
			posts: [],
			$scroller: {}
		};
	},
	methods: {
		ck() {
			console.log('88');
			this.$data.$scroller.innerText = '888888888888';
			console.dir(this.$data);
		}
	},
	mounted() {
		this.$data.$scroller = this.$el.querySelector('#scroller');
		// console.log(this.scroller);

		// var IScroll = $.AMUI.iScroll;
		// document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
		// this.$nextTick(() => {
		// 	var myScroll = new IScroll('#wrapper', { scrollbars: true });
		// 	console.log(myScroll);
		// });

		var data = {
			msg: '',
			posts: [
				{
					postID: 48811244,
					title: '【资源分享】🔥独家实时变声器🔥和平王者QQ网恋 小哥哥一起玩',
					detail: '【软件名称】魔音变声器\n\n【软件语言】中文\n\n【软件大小】30.25m\n\n【软件版本】1.5.1\n\n【软件包名】\ncom.putaotec.mvoice\n【开发代号】13033\n\n【系统版本】10\n\n【特别说明】不需要付费，打开就是会员  \n\n【软件简介】变声器\n\n【下载地址】https://wwx.lanzoui.com/i9iBJr26g7i\n',
					images: ['http://cdn.u1.huluxia.com/g4/M02/42/61/rBAAdmEMmd6AcFxjAAA-KWI9560462.jpg', 'http://cdn.u1.huluxia.com/g4/M02/42/61/rBAAdmEMmeCAL5CQAAJqy44xwdw580.jpg', 'http://cdn.u1.huluxia.com/g4/M02/42/61/rBAAdmEMmeGAfZZ4AAFfRlGu694026.jpg', 'http://cdn.u1.huluxia.com/g4/M02/42/61/rBAAdmEMmeKAZQYWAAIYbEPbGUM212.jpg', 'http://cdn.u1.huluxia.com/g4/M02/42/61/rBAAdmEMmeOASMkPAAGsjDIMEtI59.jpeg'],
					score: 8,
					scoreTxt: '',
					hit: 4453,
					commentCount: 29,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628215779000,
					activeTime: 1628250298000,
					line: 0,
					user: {
						userID: 25809208,
						nick: '幻心.',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/3B/E0/rBAAdmEJC1mASLD7AABybX8zyoU474.jpg',
						gender: 1,
						age: 13,
						role: 0,
						experience: 74305,
						credits: 10,
						identityTitle: '',
						identityColor: 0,
						level: 7,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 19,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48795134,
					title: '【精品分享】全网小说、任性看-最新去会员去广告版本。',
					detail:
						'🤓🤓看我眼神行事\n\n╔════╗\n║资源信息║\n╚════╝\n▎资源名称：青芒免费小说\n▎资源版本：v 178\n▎资源大小：16.25 MB\n▎适用系统：Android 4.0 +\n\n╔════╗\n║资源简介║\n╚════╝\n青芒小说app是一款免费小说阅读器，追求极致体验的免费小说阅读器。囊括海量精品全本小说，小说全平台免费阅读。穿越，玄幻，都市，修仙，每一个类型都展现给爱阅读的你，请在青果小说探索小说大世界吧!\n╔════╗\n║资源特色║\n╚════╝\n1、免费小说，这里的小说资源非常丰富。这里聚集了数百万本高质量的小说。\n\n2、以便更多的粉丝可以找到最好的小说。每天都有许多精彩的小说与您分享。在这里查看它们。\n\n3、精选推荐会不断更新，同时会收录流行小说，使阅读更加方便。\n\n4、小说资源丰富，您可以在小说首页上看到更多的神的评论和抱怨。\n╔════╗\n║资源亮点║\n╚════╝\n\n1、懒人听书：解放双手双眼,听你所求,懒人必备!\n\n2、护眼模式：字体、亮度、仿真、滚屏、背景统统可以设置,更贴心!\n\n3、强大搜索：拥有强大搜索功能,帮助你搜索你想要的书籍!\n\n4、离线无广告：一键下载作品到本地，离线阅读，再无广告烦扰！\n\n5、特色书架：智能书架,图书更新章节自动提醒!\n╔════╗\n║资源下载║\n╚════╝\n\nhttps://wwi.lanzoui.com/iqdS8s7uadi\n\n何为三无产品：\n\n无注册登录界面，不怕账号信息获取泄露\n无推广邀请界面，不用做任务也能免费玩\n无积分系统机制，积分换钱？假的你也信\n\n能换源，能听书，全本小说真的全免费',
					images: ['http://cdn.u1.huluxia.com/g4/M03/3E/18/rBAAdmEKO9yATISlAAMhe1h5UJQ845.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3E/18/rBAAdmEKO9yADJSBAAM4YmfwT-s073.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3E/18/rBAAdmEKO92AbnHKAAKlhtA8-o4213.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3E/18/rBAAdmEKO96AAc8-AAHbhsW6uWM815.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 4475,
					commentCount: 42,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628060638000,
					activeTime: 1628250791000,
					line: 0,
					user: {
						userID: 24310270,
						nick: '搞事情了',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/2C/C5/rBAAdmBd2vuAEYgLAAHFFR1NiME189.jpg',
						gender: 1,
						age: 26,
						role: 0,
						experience: 15305,
						credits: 31,
						identityTitle: '',
						identityColor: 0,
						level: 5,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 11,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48798543,
					title: '【Android】美图秀秀🔥 强大P图软件🔥内涵VIP会员版',
					detail:
						'<text>VIP版本，心动不←_←[滑稽]P图必备[haha]\n\n\u200c还是那句话你们的点赞和关注是楼主发帖的动力[爱心]\n\u200c       💥 注意：推荐使用夸克浏览器下载💥\n              本人就是用夸克的亲测没问题</text><image>http://cdn.u1.huluxia.com/g4/M01/3E/FC/rBAAdmEKmueAHpoyAACyDoUud28155.jpg,1069,995</image><text>\u200c       🌸关注楼主，你们每期都会有不一样的体验哦～</text><image>http://cdn.u1.huluxia.com/g4/M01/3E/FC/rBAAdmEKmuiALPQ6AAPeKseHbvs581.jpg,1353,1080</image><text>\n❌注意：软件内只能用手机号码登录哦，登录即是会员</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmumAIp5uAADL-j1d4_w591.jpg,576,540</image><text>🌈【软件名称】美图秀秀\n\n🌈【软件大小】93.34M\n\n🌈【软件版本】9.2.3.0\n\n🌈【软件包名】com.mt.mtxx.mtxx\n\n🌈【特别说明】本版本已修改VIP，手机登录就是会员\n🌈【软件介绍】：美图秀秀\n              ，，\n                         影像处理软件\n\n美图秀秀是一款很好用的免费图片处理软件，软件的操作和程序相对于专业图片处理软件如光影魔术手、Photoshop比较简单[1]。美图秀秀独有的图片特效、人像美容、可爱饰品、文字模板、智能边框、魔术场景、自由拼图、摇头娃娃等功能可以让用户短时间内做出影楼级照片。美图秀秀还能做非主流闪图、非主流图片、QQ表情、QQ头像、QQ空间图片等。美图秀秀已经通过360安全认证，中国优秀软件审核。\n🌈【软件图片】：</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmuqAXHQpAAFYz0DBLf0192.jpg,1440,1080</image><text>🎖️【修改说明】\n  1、已去除签名验证；\n  2、已解锁会员功能；\n  3、已去除可视广告；\n  4、已去除推广弹窗；\n  5、已去除更新弹窗；\n  6、已去除无效组件；\n⚡⚡【测试截图】</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmuuAUL1rAAMupD8GNek365.jpg,1440,1440</image><text></text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmuyADoqAAAJDKlAVEYE464.jpg,1920,1080</image><text> ※〔蓝奏云〕※求关注，求关注，求关注\n━━━━━━[爱心][玫瑰]━━━━━\nhttps://bsdlb.lanzoui.com/ijuhBs8iued\n密码:lb666\n含义：（李白666）\n💥注意：推荐使用夸克浏览器下载\n🌸拿走记得点赞关注\n━━━━━\n\n推荐部分教程建议小白使用哦:\n点击蓝色链接即可进入:\n#【李白原创】教你一步修改搜狗阅读VIP会员功能，解锁会员教程🔥#\n#【原创教程】教用MT管理器修改最新版某灯威屁恩，解锁专业版。#\n#【原创教程】教大家用黄鸟抓包解压缩全能王获取永久会员🔥附带软件#\n学会点赞关注噢，持续更新哈！\n━━━━━\n\nPS:这里提示一下:\n肯定安装过程中会出现报毒现象，直接继续安装即可！\n\n一一一一一一一一一一一一一一一一一一\n一一一一</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmu2AScdgAAC-ys_d6zU029.jpg,1080,494</image><text>最后关注我分享更多实用软件，记得点赞关注十一路上不迷路！\n每次都非常认真的在分享，然后咱们记得，拒绝白嫖，</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmu-AZ_y7AAPwum3vakw441.jpg,1734,1080</image><text>有葫芦的送个葫芦，没葫芦的点个关注[阴险]</text><image>http://cdn.u1.huluxia.com/g4/M02/3E/FC/rBAAdmEKmu-Ab4dPAADd0STlp58965.jpg,1076,641</image><text>————————\n  软件来源于网络：原创修改来自mt管理器论坛的GenW楼主\n如有侵权，联系删除。</text>',
					images: [],
					score: 54,
					scoreTxt: '',
					hit: 15325,
					commentCount: 250,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628084976000,
					activeTime: 1628250785000,
					line: 0,
					user: {
						userID: 23224785,
						nick: '【UGC】李白ღ',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/DA/A7/rBAAdmDRQk6AbSV_ACMAgUnYRVo586.jpg',
						gender: 2,
						age: 0,
						role: 2,
						experience: 52835,
						credits: 16791,
						identityTitle: '玩机大侠',
						identityColor: 4292152859,
						level: 7,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: '初入门槛',
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 59,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48677438,
					title: '【萌丫资源】酷我音乐_v9.4.4.0★解锁更多新姿势_双版本',
					detail:
						'<text>酷我音乐-听音乐用酷我</text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64pWAfeySAAA-L20ITVw836.png,750,450</image><text>╔════╗\n║资源信息║\n╚════╝</text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64pWAOhVxAAAc7pljEsE381.jpg,512,512</image><text>▎资源名称：酷我音乐\n▎资源版本：v 9.4.4.0\n▎资源大小：68.10 MB\n▎适用系统：Android 4.0 +</text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64pWADRDuAALotLdxCV071.jpeg,1080,1439</image><text>╔════╗\n║修改说明║\n╚════╝\n\n解锁特性：『本次更新解锁优化共计 24 处』\n\n1、解锁SVIP会员，解锁SVIP会员极速下载\n2、解锁单曲购买\n3、解锁专辑微信内购\n4、点亮vip图标，解锁会员音效，动效\n5、解锁灰色版权歌曲\n6、去除所有广告\n7、解锁主题下载\n8、去除启动页广告\n9、解锁酷我畅听vip书籍（只能听，付费的不能下）\n10、解锁海外歌曲\n11、默认进入『我的』界面🆕\n12、去除版本更新\n\n『精简版（在功能版的基础上对布局进行精简优化）』\n\n13、去除我的页面直播入口，发现、活动\n14、精简我的页面\n15、精简侧边栏list\n16、去除首页轮播图\n17、去除首页界面广告banner\n18、去除首页界面直播分栏\n19、去除我的界面会员中心view\n20、去除酷我音乐启动音效🆕\n21、修改『关于界面』版本号显示不全的问题🆕\n22、去除首页下滑的直播推荐入口🆕\n23、去除播放界面推荐主播正在唱dialog🆕\n24、去除侧边栏消息小红点🆕</text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64paAQCWZAAGn4BxdiaQ985.jpg,3464,3464</image><text></text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64peAe0gWAANbrxrxJXA940.jpg,3464,3464</image><text></text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64piAZC6fAAHB5oiXP6c619.jpg,3464,3464</image><text>\n【特别说明】：\n\n在使用过程中有任何建议或者意见请直接留言评论，我会在第一时间处理\n\n【禁止搬砖二改】\n╔════╗\n║下载链接║\n╚════╝\n\n精简版（极力推荐）\n\nhttps://3lourain.lanzoui.com/iIFl2rs5b4f\n\n功能版：\n\nhttps://3lourain.lanzoui.com/ib1ufrs5aid\n\n╔════╗\n║往期精品║\n╚════╝\n#【萌丫资源】点点听书★完美收录11个平台汁源！！#\n\n#【萌丫资源】Fotor照片编辑器_解锁价值198的高级会员#\n\n#【萌丫】手机P图的软件★把妹子P成男神#\n\n╔════╗\n║免责声明║\n╚════╝\n\n1、资源来源于网络，官包版权归原作者所有，修改版的版权归本人所有，转载请跟我联系，取得同意后方可转载，保留追究权利！！\n\n2、禁止对本修改资源进行二次修改及篡改原创信息；\n\n3、所有的修改作品仅供学习和测试，请在24小时内将其删除。请勿用于任何盈利用途，如果喜欢，请支持正版；\n\n4、所有的作品均经过发布者本人的测试，但不保证兼容所有的手机硬件和同机安装的其他软件，您必须自行承担所有可能因使用汉化软件而产生的风险；\n\n5、如果发布者的作品侵害了您的版权，请与管理员取得联系，我们将在第一时间解决，预计将在3个工作日内给您回复。\n\n</text><image>http://cdn.u1.huluxia.com/g4/M00/22/FF/rBAAdmD64piATBS1AAIW-vRzruM380.jpg,3464,1882</image><text>#【邀请函】社区最热门版块向你发出邀请#\n\n#【邀请函】社区最热门版块向你发出邀请#\n</text>',
					images: [],
					score: 22,
					scoreTxt: '',
					hit: 26509,
					commentCount: 306,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1627054745000,
					activeTime: 1628250734000,
					line: 0,
					user: {
						userID: 9904404,
						nick: 'Rain〃萌丫吖',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/13/4D/rBAAdmDyMtmASubWAAEQa0fWVNQ487.jpg',
						gender: 1,
						age: 0,
						role: 0,
						experience: 230715,
						credits: 4675,
						identityTitle: '三当家',
						identityColor: 4292152859,
						level: 11,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: '鲜有人知',
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4304,
					status: 0,
					praise: 200,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48683487,
					title: '【资源分享】好多动漫，二次元小伙伴必备神器！',
					detail: '【软件名称】：好多动漫\r\n\r\n【软件版本】： v5.0.8\r\n\r\n【软件大小】：16.6M\r\n\r\n【软件介绍】：好多动漫是一个以二次元文化为基调，动漫游戏美图为核心的ACG玩家社区。\r\n\r\n是千万喜欢二次元美图玩家的福利圣地，不论你是喜欢动漫、漫画，二次元、游戏、cosplay，这里都能找到兴趣相投的小伙伴，二次元的大门等你打开！\r\n\r\n无广告纯净版！\r\n\r\n【下载地址】: https://wws.lanzoui.com/iFysQrtvp8f\r\n密码:0000',
					images: ['http://cdn.u1.huluxia.com/g4/M00/24/4D/rBAAdmD71xqAEDGlAALKneTqtiQ490.jpg', 'http://cdn.u1.huluxia.com/g4/M01/24/4D/rBAAdmD71xuAcOkoAAQN4hJrVw0764.jpg', 'http://cdn.u1.huluxia.com/g4/M01/24/4D/rBAAdmD71xuAF8i_AAMFallAWfY986.jpg'],
					score: 7,
					scoreTxt: '',
					hit: 42921,
					commentCount: 158,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1627117340000,
					activeTime: 1628250710000,
					line: 0,
					user: {
						userID: 25969106,
						nick: '想吃芊芊',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/23/FB/rBAAdmD7re6AQLDGAAF9TCXlFMQ666.jpg',
						gender: 1,
						age: 0,
						role: 0,
						experience: 5570,
						credits: 7,
						identityTitle: '',
						identityColor: 0,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 119,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48797928,
					title: '【分享】抽签神器，朋友聚会分工任务抽签，帮你快速做出选择',
					detail: '【楼主点评】：聚会，外出野炊，分工任务安排，可以用抽签神器，支持好友抽签，抽到什么全凭运气\n\n【微信小程序】：抽签神器\n\n【小程序版本】：2.17\n\n【小程序大小】：0M\n\n【小程序平台】：安卓Android/苹果ios\n\n【测试机型】：红米k40\n\n【使用说明】：微信小程序里搜索名字或者扫码就可以进去使用了\n【使用方式】：直接打开微信小程序搜索“ 抽签神器 ” 或者用微信扫描下方的小程序码哦\n打开方式建议：保存下方小程序二维码，微信扫一扫快一点哦(´-ω-`)\n\n不喜勿喷哦拿走请评论。[玫瑰]\n\n不喜勿喷哦拿走请评论。[玫瑰]\n\n不喜勿喷哦 拿走请评论。[玫瑰] \n\n',
					images: ['http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjlaAQK-IAAC56cKMYJU059.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjlaAXTaAAACxyveYrfo949.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjlaAEvNpAANzfTyMTUc565.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjleAfq6KAAQSW0yYDu8122.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjleAWwn0AAIsHRP0dqg782.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/D7/rBAAdmEKjliASAnjAAN1QCEoRw0954.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 727,
					commentCount: 10,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628081752000,
					activeTime: 1628250679000,
					line: 0,
					user: {
						userID: 25812397,
						nick: '梦梦呀呀',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/3E/DF/rBAAdmEKkUKAPi5sAAE9Zfb_rho318.jpg',
						gender: 1,
						age: 16,
						role: 0,
						experience: 58110,
						credits: 3,
						identityTitle: '',
						identityColor: 0,
						level: 7,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 1,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48702260,
					title: '【资源分享】WPS Office解锁高级版，最好用的移动办公软件',
					detail: '【软件名称】WPS Office\r\n\r\n【软件语言】中文\r\n\r\n【软件版本】v14.6\r\n\r\n【软件大小】117.23M\r\n\r\n【软件介绍】wps是比较符合小白类朋友使用的，比较简单直观，功能强大，各种word文件都能打开。而WPS手机版更是移动端的办公利器。\r\n\r\n最佳安卓办公软件，个人版永久免费，体积小、速度快；独有手机阅读模式，字体清晰翻页流畅；完美支持微软Office、PDF等23种文档格式；文档漫游功能，让你离开电脑一样办公。\r\n\r\n* 解锁高级版（要求：需要登陆任意账户才能解锁）\r\n﹂免广告，所有的高级功能及在线高级模板免费用\r\n﹂PDF工具含：PDF编辑、PDF签名、PDF提取等\r\n﹂PDF转Word、图片转PDF格式、保存为长图片\r\n﹂OCR、添加水印、合并文档、文档瘦身等功能\r\n\r\n【软件下载】：https://cloud.189.cn/web/share?code=jU7bE3JvEney',
					images: ['http://cdn.u1.huluxia.com/g4/M03/28/61/rBAAdmD-LS6AFIFNAAQSJtWRXKM387.jpg', 'http://cdn.u1.huluxia.com/g4/M03/28/61/rBAAdmD-LS-AALRaAAPRdCHysyA061.jpg', 'http://cdn.u1.huluxia.com/g4/M03/28/61/rBAAdmD-LS-ADKLhAAMQM5wlgI4567.jpg', 'http://cdn.u1.huluxia.com/g4/M03/28/61/rBAAdmD-LTCAIgFUAAObEw566f8152.jpg'],
					score: 12,
					scoreTxt: '',
					hit: 38121,
					commentCount: 235,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1627270449000,
					activeTime: 1628250679000,
					line: 0,
					user: {
						userID: 25804153,
						nick: '超级科技宅',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/7B/E6/rBAAdmCU3PuAZPiQAAFRRkeULDk687.jpg',
						gender: 2,
						age: 0,
						role: 0,
						experience: 6135,
						credits: 17,
						identityTitle: '',
						identityColor: 0,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 344,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48814897,
					title: '【分享】轻启动  为你去掉广告的烦恼',
					detail:
						'<text></text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHX2AHPS4AAGDPw3xo1k724.jpg,1152,1076</image><text>\n╔════╗\r\n║资源介绍║\r\n╚════╝\n\n很多APP启动时都会出现启动页。这会拖慢APP启动速度、增加耗电量，如果一不小心点错了，还会唤起其他APP,令人反感。</text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHX2ANGvOAAEeVxNU-hw544.jpg,1000,1500</image><text>\n\n「轻 启动」可以帮您自动跳过这些启动页，大幅提升APP启动速 度，节省电量。\n\n曾几何时，为了提升一点点的APP启动速度，我们需要购买更好的手机，安装各种内存清理软件。而现在，我们只需使用「轻启动」，就能跳过冗余的启动页，大幅提升APP启动速度。\n\n「轻启动」采用独家技术方案，无需Root手机，且耗电量极低，赶紧来试试吧~\n</text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHX-ASSHEAAI2JUF-R9I552.jpg,1080,810</image><text>╔════╗\r\n║应用名称║\n╚════╝</text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHYWAZ1y0AAAvztoykC8542.jpg,1068,140</image><text>\n╔════╗\r\n║应用版本║\r\n╚════╝\nv2.19.0\n╔════╗\r\n║应用大小║\r\n╚════╝\r\n2.4mb\n╔════╗\r\n║下载地址║\r\n╚════╝\n\nhttps://wwr.lanzoui.com/iNdrBsb54dg 密码:hbww\n</text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHYWAYtZaAABWEIoxSVc653.jpg,640,215</image><text>#【邀请函】社区最热门版块向你发出邀请#\n\n欢迎你们来参加</text><image>http://cdn.u1.huluxia.com/g4/M00/43/85/rBAAdmENHYaAC6vhAAC5Qs9PIhU157.jpg,1137,427</image><text></text>',
					images: [],
					score: 5,
					scoreTxt: '',
					hit: 211,
					commentCount: 14,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628249479000,
					activeTime: 1628250677000,
					line: 0,
					user: {
						userID: 4294478,
						nick: '青笺[蜷]',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/40/95/rBAAdmELnVCAXi-RAADrjev8Rkk412.jpg',
						gender: 1,
						age: 20,
						role: 2,
						experience: 128680,
						credits: 52107,
						identityTitle: '渗透专家',
						identityColor: 4281571635,
						level: 9,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: '籍籍无名',
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 1,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48795038,
					title: '【分享】Office Tool Plus v8.2.4.0',
					detail:
						'部署 Office（包含下载、安装、激活、管理）\n部署 Office（包含下载、安装、激活、管理）\n部署 Office（包含下载、安装、激活、管理）\n\n【应用名称】Office Tool Plus v8.2.4.0\n\n【应用版本】v8.2.4.0\n\n【应用大小】13.75MB\n\n【应用介绍】Office Tool Plus（简称OTP）是一款微软Office办公软件下载、安装、管理的辅助增强工具。它可以快速自定义部署，[真棒]在线下载安装 Office 的各个版本[真棒]，也可以通过已有的离线安装文件来部署Office镜像，[哈哈]同时在安装过程中你可以自由选择安装哪些需要使用的组件， 在安装之后也可以单独来安装某个需要的组件。[惊讶]\n\n【更新日志】\n2021.07.27 v8.2.4.0\r\n\r\n* 支持使用应用程序内命令部署 Office。\n\n* 支持在导出配置时读取 Remove 元素的语言属性。\n\n* 修复了内存不足无法继续执行程序的问题。\n\n* 修复了某些情况下 Office 许可证加载异常的问题。\n\n* 修复了其他问题并改进了性能。\r\r\n\n最近更新：\r\r\n更新Office 2021数据。\r\n\r\n更新部署模式以编辑配置，下载，安装和创建ISO。\r\n\r\n支持在下载Office时添加下载任务，例如，当您下载32位Office，切换到64位并单击“开始部署”时，下载任务将添加到列表中。\r\n\r\n支持使用快捷键Ctrl + L（在部署页面上）安装iSlide 。\r\r测试KMS主机时，如果vlmcs不存在，则Office Tool Plus将使用Tcping来测试主机。\r\n\r\n支持使用命令args启动和部署Office，请参阅RunMe.bat中的详细信息，并使用文本编辑器打开文件。\r\n\r\n现在可以通过按按钮打开应用程序内命令，然后删除Ctrl +P。\n\n【支持产品】\nMicrosoft 365[惊讶]\r\r\n\nOffice 2021、2019、2016[惊讶]\r\r\n\nVisio Online Plan 2 & 2021、2019、2016[惊讶]\r\r\n\nProject Online Desktop Client & 2021、2019、2016[惊讶]\n\n【功能介绍】\n\n部署 Office（包含下载、安装、激活、管理）[真棒]\r\r\n\n查询通道版本，自定义安装Office产品，语言包[太开心]\r\r\n\n设置优化、修复/重置、导出/导入XML配置文件\r\r添加产品、应用程序、语言包至现有的Office中\r\r\n\n卸载Office一个或多个产品、应用程序、语言包\r\r\n\n支持在线激活、电话激活、KMS激活[惊讶]\r\r\n\n安装、卸载 Office 许可证（转换 Office 版本）[哈哈]\r\r\n\n管理 Office 的 KMS 激活，一键清理许可证密钥[吐舌]\r\r\n\n更改 Office 的更新通道而无需重新安装 Office[真棒]\r\r\n\n支持批量转换文档：转换Office文档为其它格式\r\n\n【运行要求】\n\n.NET 5.0 Desktop Runtime x86（安装见安装说明）\n\n\rWindows 10, Windows Server 2019\n\n【下载链接】阿里云盘https://www.aliyundrive.com/s/AWnkBBpDtP5不会用阿里云链接的看这个帖子（点击下面即可跳转）#阿里云盘压缩文件分享小工具 v1.0.0.0（windows）#\n\n天翼网盘https://cloud.189.cn/web/share?code=RRV3y2uQvE3a\n\n百度网盘https://pan.baidu.com/s/1U1qhcmjgqsfFBVqPpqSMlw 提取码:6666\n\n【亲测截图】\n',
					images: ['http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI2Ae1fwAACi02VRg-w868.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI2AatZjAACkqaXIEn0905.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI6AddKWAADKOoRXwOM379.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI6ADJg4AACEM8Cmg5M924.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI-AD0SyAACXKOsm8LY468.jpg', 'http://cdn.u1.huluxia.com/g4/M02/3E/0F/rBAAdmEKOI-AIwheAACdL3YcD28437.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 1823,
					commentCount: 42,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628059791000,
					activeTime: 1628250671000,
					line: 0,
					user: {
						userID: 10201994,
						nick: 'mo王',
						avatar: 'http://cdn.u1.huluxia.com/g1/M00/11/5C/wKgBB1baTSGASVxbAAEJ5v1ypRI5384.ht',
						gender: 2,
						age: 25,
						role: 0,
						experience: 8100,
						credits: 32,
						identityTitle: '',
						identityColor: 0,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 25,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48814493,
					title: '【原创修改】天翼云盘v8.9.0铂金会员解锁版',
					detail:
						'另外精简了布局[滑稽][玫瑰][玫瑰][玫瑰]\n【应用名称】：天翼云盘\n\n【应用版本】：8.9.0\n\n【应用大小】:   166MB\n\n【使用平台】：Android\n\n【版本说明】：\n    ◎解锁部分会员功能\n  \n    ◎去除更新提示\n\n    ◎去除广告\n\n    ◎精简布局\n\n【官方介绍】：\n      天翼云盘是中国电信面向个人及家庭用户推出的云存储服务产品，定位“个人与家庭的数据中心“，为个人及家庭用户提供手机相册备份、多端文件共享、家庭相册分享、云端视频回看等云存储服务。天翼云盘能为你做什么？\n1. 极速传输\n中国电信专属的极速传输通道\n央企级安全保障\n全程多重加密传输，防钓鱼防盗更安全可靠\n2. T级存储\n可存超百万张照片、上万部高清视频\n3. 自动备份\n手机相册、视频自动备份，同时支持微信文件备份\n4. 家庭相册\n照片智能识别和分类管理，可按时间、人物、地点搜索\n5. 家庭共享\n邀请家人加入家庭云空间，一人上传文件，电视、电脑同步浏览，全家共享\n6. 云回看\n手机一键看家，不受时间地点限制，随时回看哪些人在用天翼云盘。\n\n【下载链接】：\n◎天翼云盘链接：https://cloud.189.cn/t/222AjmqUZvQj\n◎百度网盘链接:\nhttps://pan.baidu.com/s/1vEcH6wJmJoZVQ_juGOgeDw \n提取码:6666\n\n注:由于最新版本已被官方加固，太麻烦脱壳了，所以修改的是8.9.0版的[滑稽][茶杯]',
					images: ['http://cdn.u1.huluxia.com/g4/M01/43/6B/rBAAdmENEq6AO5AMAAFO-6m_weg946.jpg', 'http://cdn.u1.huluxia.com/g4/M01/43/6B/rBAAdmENEq-AYWH8AAFOCYkPEaM624.jpg', 'http://cdn.u1.huluxia.com/g4/M01/43/6B/rBAAdmENEq-AR4gGAAA4JpMpiMI312.jpg', 'http://cdn.u1.huluxia.com/g4/M01/43/6B/rBAAdmENErCADHHbAAFtCwVYwSc046.jpg', 'http://cdn.u1.huluxia.com/g4/M01/43/6B/rBAAdmENErCAfs7fAAG5OjQ4i_Q575.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 229,
					commentCount: 6,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628246705000,
					activeTime: 1628250670000,
					line: 0,
					user: {
						userID: 18505557,
						nick: '肖炎药',
						avatar: 'http://cdn.u1.huluxia.com/g3/M00/53/73/wKgBOVwc1PSAVLgmAAB_Io-77Z0298.jpg',
						gender: 2,
						age: 17,
						role: 0,
						experience: 27750,
						credits: 416,
						identityTitle: '',
						identityColor: 0,
						level: 6,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: '初入门槛',
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 3,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48788818,
					title: '【精品分享】全网小说、漫画任性看-最新去会员去广告版本',
					detail:
						'╔════╗\n║资源信息║\n╚════╝\n▎资源名称：爱阅读\n▎资源版本：v10001\n▎资源大小：31.6 MB\n▎适用系统：Android 4.0 +\n\n╔════╗\n║资源简介║\n╚════╝\n热门小说、热门漫画、小说电子书、小说阅读器！小说内容包括校园青春，都市言情，玄幻爱情，穿越爱情，新书不断，全网最快时间更新，精彩读书尽在爱阅读！\n【超大书架】多种本地图书导入方式，书架含图书排序、分类等多种贴心功能。\n【海量书库】30 万册图书书城，包括了各种精品出版物与网络原创小说。\n【新增漫画】热门、经典漫画一应俱全，二次元的你快来体验吧！\n【手指笔记】以「指」代笔，随时摘取精彩内容，真正实现读书不忘！\n【离线阅读】跨终端数据同步，享受高速流畅的离线阅读体验。\n【个性排版】自定义阅读界面排版。\n【免费图书】每日为读书人提供各种不同的免费正版图书，包括免费原创小说及精品出版物。\n【追书提醒】提供最新小说追书提醒，第一时间看更新。\n【书荒书单】各种书单，方便读书人书荒找书。\n\n╔════╗\n║资源下载║\n╚════╝\n\nhttps://wwi.lanzoui.com/i7Fecs6zdcj\n',
					images: ['http://cdn.u1.huluxia.com/g4/M00/3C/7C/rBAAdmEJRQOAfGI4AALdp5M78SM167.jpg', 'http://cdn.u1.huluxia.com/g4/M00/3C/7C/rBAAdmEJRQSATEbwAAOKWJDKG9A048.jpg', 'http://cdn.u1.huluxia.com/g4/M00/3C/7C/rBAAdmEJRQSAX4BHAATZlPL21Xo609.jpg', 'http://cdn.u1.huluxia.com/g4/M00/3C/7C/rBAAdmEJRQWAeUqqAAKrcukbLb0000.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 11026,
					commentCount: 76,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1627997445000,
					activeTime: 1628250634000,
					line: 0,
					user: {
						userID: 24645783,
						nick: '昵称不想改',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/75/94/rBAAdl_sN0KAD5AOAABc_F3l-3Q469.jpg',
						gender: 2,
						age: 26,
						role: 0,
						experience: 7690,
						credits: 6,
						identityTitle: '',
						identityColor: 0,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 24,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48707564,
					title: '【分享】Tenta浏览器🔥高级版🔥深夜必备！秒播P站推特！！',
					detail: '秒杀UPX！解锁所有外国线路！[玫瑰]可访问油管！推特！P站！[玫瑰]速度来！！！\n\n软件名称：Tenta高级版\n\n软件大小：67.04M\n\n软件版本：4.0.55 (2842)\n\n软件介绍：\n一款超强大的浏览器来袭，与upx一样内置某X功能，并且多达20+条线路，可随意切换，让你轻松浏览Q球小姐姐，功能也很强大，自带有去广及下载功能，视频1080P画质随便切换无限制！先看说明！\n\n已去广告，已去升级，已破解收费节点！\n\n下载地址：https://wwr.lanzoui.com/iQGVurvv1gb\n[灯泡]第一次用一定要看！[阴险]一定要看！[怒]一定要看！不然用不了别怪我！\n每次退出软件需要从软件退出，看图5！不然浏览网页会出现闪退的情况！如果浏览网页出现闪退了点退出按钮再重新进一遍即可！\n\n素质三连，拿软件先顶帖！！[玫瑰]\n素质三连，拿软件先顶帖！！[玫瑰]\n素质三连，拿软件先顶帖！！[玫瑰]\n',
					images: ['http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-sm2AO4GfAABQAIyRiJI515.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-sm6Aclg3AAHxCcu7irw109.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-sm6AZrnLAAO2sDkHDvc111.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-sm-AGsEXAAJ6CwWLUSA134.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-snCAClf1AAKqeYZ76eo109.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-snCARhzpAAFIFptO7VA719.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-snGAL6RtAADOQYWjE9U706.jpg', 'http://cdn.u1.huluxia.com/g4/M03/29/85/rBAAdmD-snKACT81AAEU73EO96U862.jpg'],
					score: 35,
					scoreTxt: '',
					hit: 256464,
					commentCount: 1558,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1627304562000,
					activeTime: 1628250632000,
					line: 0,
					user: {
						userID: 23768758,
						nick: 'BloodWMo',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/3A/6B/rBAAdmEIDZmAbpLHAAFbnZ0Mop0825.jpg',
						gender: 1,
						age: 20,
						role: 0,
						experience: 9870,
						credits: 1255,
						identityTitle: '一见钟情',
						identityColor: 68709380367,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 2081,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48802322,
					title: '【小程序】全网高清动态壁纸 套图服务 精美头像应有尽有~',
					detail: '外面是看不到的，快进来-\n\n【名称】图小圈\n\n【版本】2.5.2\n\n【适用平台】安卓/iOS\n\n【软件介绍】图小圈是一款手机壁纸小程序，vx搜索：图小圈 ，也可以直接扫描下方二维码直接进入，小程序拥有丰富的壁纸资源，6k动态壁纸，套图服务，精美头像，和更多小姐姐壁纸 一键下载设置，可以让用户的手机更个性酷炫，如果您有好看的壁纸也可以直接投稿到小程序里面。觉得不错的朋友欢迎前来下载使用。',
					images: ['http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvGyAeKdtAAKcU7ohViw423.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvG2AB8ODAAIkLMHL9pI818.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvG-ACBLIAAGqeeBnUxY828.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvHCAQVKbAALrVEI1e_M597.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvHKAOZbcAAMDwZXZjcw401.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvHWABwVaAANOZuXRCAs261.jpg', 'http://cdn.u1.huluxia.com/g4/M03/42/A3/rBAAdmEMvHaAGlc7AAFKqgF0XSY139.jpg'],
					score: 7,
					scoreTxt: '',
					hit: 1627,
					commentCount: 33,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628130822000,
					activeTime: 1628250631000,
					line: 0,
					user: {
						userID: 9227201,
						nick: '柠•ั萌酸๑',
						avatar: 'http://cdn.u1.huluxia.com/g3/M03/75/51/wKgBOVqCYOyAHUlRAABMmoRhBEI1772.ht',
						gender: 1,
						age: 26,
						role: 0,
						experience: 42465,
						credits: 36,
						identityTitle: '',
						identityColor: 0,
						level: 7,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 13,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48810449,
					title: '【资源分享】36漫画去广告版',
					detail: '应用：36漫画\n\n版本 ：9.0.197\n\n大小 ：11.5M\n\n系统 ：安卓\n\n语言 ：中文\n\n修改：去广告版，个人觉得还不错\n\n应用介绍：\n36漫画是一款可以免费看小说和漫画的神器，给大家分享的版本已经去除全部广告，无需登录就可以使用，非常奈斯。\n\n应用链接:https://xjes.lanzoui.com/igGDfrynrne\n\n拿走吱一声，记得关注一下，以后就是老粉了[滑稽][玫瑰]\n\n新人求葫芦[委屈][委屈][委屈]',
					images: ['http://cdn.u1.huluxia.com/g4/M01/42/2D/rBAAdmEMcwqAacoOAAJ0zF5QO3c216.jpg', 'http://cdn.u1.huluxia.com/g4/M01/42/2D/rBAAdmEMcwuAXVqiAAMU1Kh69NU739.jpg', 'http://cdn.u1.huluxia.com/g4/M01/42/2D/rBAAdmEMcwyAUplFAAFNk-zY_Fs913.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 1967,
					commentCount: 27,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628205836000,
					activeTime: 1628250616000,
					line: 0,
					user: {
						userID: 22274270,
						nick: '萌二1',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/3F/F0/rBAAdmELVIWAZJv0AAFXvpwf5YQ293.jpg',
						gender: 2,
						age: 1,
						role: 0,
						experience: 2120,
						credits: 5,
						identityTitle: '',
						identityColor: 0,
						level: 3,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 16,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48813498,
					title: '【分享】微信自动回复（附超详细步骤）',
					detail: '软件名称:微X模块\n软件大小:3MB\n软件链接:https://wwr.lanzoux.com/iXb60sav6xi\n密码1234\n软件功能:防撤回、自动回复等等\n软件使用方法:配合太极使用\n1.下载太极（葫芦侠主页搜），下载微X模块\n2.打开太极，渡劫微信【图1】会提示删除原微信，然后重新安装\n3.渡劫成功后装好模块（太极叫法宝）【图2】\n4.打开微信，点击设置，会出现微X模块，然后点击，在然后点击自动回复【图3】\n5.再开启总开关，再点击设置机器人【图4】\n6.机器人要设置茉莉机器人（经过测试，茉莉免费）【图5】\n7.点击下面的链接，自动跳浏览器，然后注册一下，会给俩条东西，复制到微X模块茉莉机器人那【图6】\n8.没了，如果没效果，请到好友主页，点微信模块，并开启机器人【图7】\n注意事项:微信重装后会丢失数据，有重要资料的请备份！\n',
					images: ['http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM84yAcADgAALzET98Z_U912.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM842AcESCAALdOaoCvgI429.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM842AKd13AAGfXuhg3Fc958.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM846AQADOAAGPCCHqV_Y761.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM84-AUlNKAARTAFs7TXA475.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1E/rBAAdmEM85CAY8AnAARvCqd0pYo810.jpg', 'http://cdn.u1.huluxia.com/g4/M02/43/1F/rBAAdmEM85GAHYjfAAIgL0BcRI0500.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 575,
					commentCount: 16,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628238737000,
					activeTime: 1628250605000,
					line: 0,
					user: {
						userID: 22815905,
						nick: '英九',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/0E/75/rBAAdmDu_a6ALTMEAACgXhkKoCk007.jpg',
						gender: 2,
						age: 1,
						role: 0,
						experience: 16770,
						credits: 1,
						identityTitle: '',
						identityColor: 0,
						level: 5,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 3,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48812035,
					title: '【资源分享】耳音Asmr - 让睡眠充满质量 - 睡眠神器',
					detail: '应用名称：耳音Asmr\n\n应用大小：9.36MB\n\n应用版本：v10.23.01\n\n应用环境：安卓\n\n应用介绍：提高人体睡眠质量，边看妹子边提供睡眠质量，带上耳机效果更佳，相信我使用完你会来感谢我的，注册就是永久会员，无充值通道，类型视频很多，有效解决失眠的朋友，\n\n功能特点：支持视频后台播放，音频后台播放，支持在线下载，离线手机观看。无会员限制。\n\n别做伸手党[呵呵][呵呵][呵呵][呵呵]\n拿走吱声[呵呵][呵呵][呵呵]\n\n应用下载：https://wwi.lanzoui.com/imkE9sakxqh\n\n应用效果图：\n',
					images: ['http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMuimAL1z3AAIbotQ3px4275.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMuiqAHb0AAAHyZX6tezQ075.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMuiuAFoyCAAHdstGjql4996.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMuiuAG29DAAFZIII3XvA492.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMuiyAYCutAAF-8lMw8fo882.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMui2AOB7RAAGwrZ3FqwM259.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMui2AYqo-AAHAcSdN5ZM889.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMui6ASOW7AAQuSO6kftc058.jpg', 'http://cdn.u1.huluxia.com/g4/M00/42/9F/rBAAdmEMui-AakTtAAHAXoct3Lg337.jpg'],
					score: 0,
					scoreTxt: '',
					hit: 1205,
					commentCount: 31,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628224047000,
					activeTime: 1628250587000,
					line: 0,
					user: {
						userID: 19371437,
						nick: '趣无止境',
						avatar: 'http://cdn.u1.huluxia.com/g3/M00/1F/AA/wKgBOVzhGM6AdjevAACyzzyhRJY576.jpg',
						gender: 2,
						age: 19,
						role: 0,
						experience: 16535,
						credits: 5,
						identityTitle: '',
						identityColor: 0,
						level: 5,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 5,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48798990,
					title: '【深海share】启阅小说v2.2.6',
					detail:
						'<text></text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCeAZHN6AADxtuhz5Qc736.jpg,1000,1000</image><text></text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCeAfOrAAAEna_GKKCQ927.jpg,1449,752</image><text>\n【应用名称】：启阅小说\r\n\r\n【应用版本】： v2.2.6\r\n\r\n【应用大小】：9.9\r\n\r\n【软件介绍】：免费纯净无广告的看小说软件，全网免费小说聚合应用，内置1000+个免费书源和有声听书，支持书源管理、自建规则优化书籍质量，支持换源、离线下载、自动翻页、个性化阅读背景等实用的功能。\r</text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCeAM9CEAAIR_71aJak511.jpg,1080,2340</image><text></text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCiAEnUsAAE3gg2DZpw683.jpg,1080,2340</image><text></text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCiAJeEHAAI-h9Rn0do407.jpg,1080,2340</image><text>\r\n【下载地址】:  https://wws.lanzoui.com/iQQL7s8nq4j 密码:cq14\n</text><image>http://cdn.u1.huluxia.com/g4/M01/3F/19/rBAAdmEKpCmABKYDAABoP98qVBY852.jpg,678,254</image><text></text>',
					images: [],
					score: 0,
					scoreTxt: '',
					hit: 1202,
					commentCount: 11,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628087337000,
					activeTime: 1628250566000,
					line: 0,
					user: {
						userID: 25993398,
						nick: '【Rain】深海',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/BA/99/rBAAdmC-r8-AMhDLAAAtEuDFH-8968.jpg',
						gender: 2,
						age: 0,
						role: 0,
						experience: 19260,
						credits: 947,
						identityTitle: '搬砖的',
						identityColor: 4278299901,
						level: 5,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: '初入门槛',
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 2,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48808240,
					title: '【资源分享】看世界🌏浏览器📖功能强大支持小说漫画',
					detail: '浏览器可以支持各种图文插件🔥支持各大网站🔥还可以免费看海量小说漫画\n\n【应用名称】： 看世界\n\n【应用版本】： 1.6.0\n\n【应用大小】： 17.8 MB\n\n【支持平台】： 安卓\n\n【测试手机】:  小米\n\n【官方介绍】: \n免费 无需注册登录 功能强大 看世界APP是一款可以检索小说漫画为主的浏览器工具，无需注册登录。集合了1000+ 插件，拥有海量小说漫画资源，永久免费。并且辅助新型浏览器技术为用户搜索各类资源并进行浏览器的延展优化浏览；支持多家平台和扩展资源的浏览，浏览器与小说漫画并存~~~\n\n【下载链接】: \nhttps://wwr.lanzoui.com/kanshijie\n\n拿走吱一声~~\n\n',
					images: ['http://cdn.u1.huluxia.com/g4/M01/41/94/rBAAdmEL9KKAax-6AAN2caCHJ28626.jpg', 'http://cdn.u1.huluxia.com/g4/M01/41/94/rBAAdmEL9KOALeo_AALq3MUcHmU279.jpg', 'http://cdn.u1.huluxia.com/g4/M01/41/94/rBAAdmEL9KOAN1G8AAI_7d0czgI598.jpg', 'http://cdn.u1.huluxia.com/g4/M01/41/94/rBAAdmEL9KSATE1lAAQ-wRQrXZc047.jpg', 'http://cdn.u1.huluxia.com/g4/M01/41/94/rBAAdmEL9KSAIBj9AAICrQL7tMg731.jpg'],
					score: 5,
					scoreTxt: '',
					hit: 6193,
					commentCount: 37,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628173476000,
					activeTime: 1628250565000,
					line: 0,
					user: {
						userID: 26347393,
						nick: '昵称786599',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/82/A9/rBAAdl7y7tiARp_rAAAa-acb1hU533.png',
						gender: 2,
						age: 0,
						role: 0,
						experience: 37020,
						credits: 2777,
						identityTitle: '',
						identityColor: 0,
						level: 6,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 22,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48792679,
					title: '【资源分享】搜书大师永久会员版，送3168个书源，最强阅读器！',
					detail: '飞卢也收入囊中，就没有看不了的小说，不服留书名！\r\n【应用名称】：搜书大师\r\n\r\n【应用版本】： v22.15\r\n\r\n【应用大小】：23.03M\r\n\r\n【软件介绍】：搜书大师，超级好用强大的小说神器，可听书、下载、添加书源，功能特别强大，添加完我给你的书源，基本就没有看不了的小说。\r\nps：搜完书建议在书源管理右边时钟一样的按钮扫描一下书源信息！搜索完记得切换对应书源！切换对应书源！切换对应书源！\r\n\r\n【导入书源教程】：书源管理，导入书源，本地导入，找到你下载的文件，导入就行了，（可能在Download文件夹）\r\n\r\n【软件下载地址】:  https://wwr.lanzoui.com/iay8qs7jnqd  密码:11\r\n\r\n【书源下载地址】:  \r\n1444个书源：https://wwr.lanzoui.com/iOkCms7jq5a  密码:11\r\n1724个书源：https://wwr.lanzoui.com/iOcPDs9plib 密码:11',
					images: ['http://cdn.u1.huluxia.com/g4/M03/3D/6C/rBAAdmEJ7UWAVssBAAE1WzuPjmI365.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3D/6C/rBAAdmEJ7UaANzZkAAPsf0W_FCI878.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3D/6C/rBAAdmEJ7UiAOHtaAAFfS4IPILI343.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3D/6C/rBAAdmEJ7UiADvEmAAEaG0mxg0g887.jpg', 'http://cdn.u1.huluxia.com/g4/M03/3D/6C/rBAAdmEJ7UmAbig7AAGP4gT5bP8029.jpg', 'http://cdn.u1.huluxia.com/g4/M01/40/CC/rBAAdmELtIWAM8a6AAFED1COrc4914.jpg'],
					score: 11,
					scoreTxt: '',
					hit: 13585,
					commentCount: 187,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1628040522000,
					activeTime: 1628250557000,
					line: 0,
					user: {
						userID: 25969164,
						nick: '韭菜的自我修养',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/D9/2F/rBAAdmDQS_GABSpTAAB-xqwXeA4910.jpg',
						gender: 2,
						age: 0,
						role: 0,
						experience: 6115,
						credits: 12,
						identityTitle: '',
						identityColor: 0,
						level: 4,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4301,
					status: 0,
					praise: 76,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48660423,
					title: '【分享】鸿梦漫社🌈超热漫画免费追（免费无广告，第一时间更新）',
					detail: '【楼主点评】：此小程序采用更快的服务器并加了导航栏等多项功能『资源更多，功能更全，速度更快』[赖皮]\n\n各种漫画每天更新，还有各种漫画推荐 让你做真正漫画达人 不需要下载 微信打开直接扫码就可以阅读漫画，里面绝无广告！\n\n【微信小程序】：鸿梦漫社💓\n\n【小程序版本】：2.1.0\n\n【小程序大小】：0M\n\n【小程序平台】：安卓Android/苹果ios\n\n【测试机型】：华为nova4e\n\n【使用说明】：微信小程序里搜索名字或者扫码就可以进去使用了\n【使用方式】：直接微信小程序搜索“鸿梦漫社” 或者用微信扫描下方的小程序码哦\n\n打开方式建议：保存下方小程序二维码，微信扫一扫快一点哦(´-ω-`)\n\n不喜勿喷哦拿走请评论。[玫瑰]\n\n不喜勿喷哦拿走请评论。[玫瑰]\n\n不喜勿喷哦 拿走请评论。[玫瑰]\n\n【注】：极小极小极小概率偶然可能遇到打开一直转圈情况，不要慌[滑稽]是因为接口太挤了，过几个小时再来看就恢复啦',
					images: ['http://cdn.u1.huluxia.com/g4/M00/1F/2D/rBAAdmD44w-AMxJTAACEwfvnOEU64.jpeg', 'http://cdn.u1.huluxia.com/g4/M00/1F/2D/rBAAdmD44xCAMiUoAAVpp5iC8mI809.jpg', 'http://cdn.u1.huluxia.com/g4/M00/1F/2D/rBAAdmD44xGAATUhAANO-XQphfg19.jpeg', 'http://cdn.u1.huluxia.com/g4/M00/1F/2D/rBAAdmD44xKAJ8dmAALPnQoMpZE36.jpeg', 'http://cdn.u1.huluxia.com/g4/M00/1F/2D/rBAAdmD44xOAcpTLAAM8Wgb6jnM057.jpg', 'http://cdn.u1.huluxia.com/g4/M01/38/E8/rBAAdmEHYpmATwwpAAC2O_FS6jc426.jpg'],
					score: 8,
					scoreTxt: '',
					hit: 54589,
					commentCount: 257,
					notice: 0,
					weight: 0,
					isGood: 0,
					createTime: 1626923796000,
					activeTime: 1628250514000,
					line: 0,
					user: {
						userID: 17114858,
						nick: '龙少🍃ˇ',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/DD/7D/rBAAdl8j1A-AdKjLAABvxGBneoE110.jpg',
						gender: 2,
						age: 0,
						role: 0,
						experience: 27285,
						credits: 28,
						identityTitle: '',
						identityColor: 0,
						level: 6,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4302,
					status: 0,
					praise: 97,
					voice: null,
					isAuthention: 0,
					isRich: 0,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				}
			],
			weightAndTopPost: [
				{
					postID: 48643691,
					title: '【公告】内容整改',
					detail: '<text>亲爱的葫芦丝们大家好：\n \n      \n近期收到部分用户反馈，社区发布的内容中涉及到的‘网盘’等下载连接里含有违规和侵权内容，我们将会对社区此类内容进行梳理，因内容数量众多，无法逐一排查，暂时对2021年之前的发帖中含有网盘的连接进行彻底整改屏蔽或删除处理，过程中如有葫芦丝发现帖子内的链接中存在违规或者侵权内容可以在意见反馈置顶帖进行截图举报反馈。\n \n此次整改若给您带来不便，我们深感抱歉！感谢大家一直以来对葫芦侠的支持与厚爱。</text><image>http://cdn.u1.huluxia.com/g4/M01/1B/3D/rBAAdmD2kBaAVTv_AABh3DCOGzE389.png,512,512</image><text></text>',
					images: [],
					score: 60,
					scoreTxt: '',
					hit: 135809,
					commentCount: 278,
					notice: 1,
					weight: 0,
					isGood: 0,
					createTime: 1626771478000,
					activeTime: 1628243536000,
					line: 0,
					user: {
						userID: 6688367,
						nick: null,
						avatar: null,
						gender: 0,
						age: 0,
						role: 0,
						experience: 0,
						credits: 0,
						identityTitle: null,
						identityColor: 0,
						level: 0,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 101,
					status: 0,
					praise: 98,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48256707,
					title: '【通知】近期一些版块调整的说明公告',
					detail:
						'<text>⒈本版只能发布实用软件类型资源\n\n①包括但不限制Android、IOS、Windows、微信小程序...等相关软件资源类型。\n\n\n————————————————————\n————————————————————\n\n\n⒉【发帖格式】\n\n■标题:\n\n【分享】应用名称+（版本号）修改版 （Android）\n\n■主题内容:\n\n软件名称：\n\n软件版本：\n\n软件大小：\n\n官方介绍：\n\n下载链接:\n\n①目前支持云盘如下截止4月，实用软件版块允许以百度云盘、360云盘、微云云盘、蓝奏云云盘、坚果云盘、天翼云盘、迅雷网盘、阿里云盘的链接分享软件\n\n亲测截图：亲测截图3张！！！\n\n\n②发布各种软件及其它相关类型资源时：\n必须加上资源 正常运行截图{最低3张}（亲测截图）\n软件介绍和相关使用说明\n\n\n③发布前请先自行测试资源是否可正常工作  是否无违反版块相关规定。\n违反本板块版规的软件，禁止通过如最常见的弹窗引流，云注入等等\n\n\n④重复资源每个同样资源(版本号等等一样)板块只能存在一个，避免屠版，造成不好的浏览\n\n\n⑤下载链接问题\n\nⅠ下载链接必须是上面的云盘\n\nⅡ直链、短链接的不通过！\n\nⅢ链接里必须是安装包，是文件夹的不过！！！\n\nⅣ帖子内无软件链接\n\n\n⑥关于求软件，求影视问题\n\nⅠ求软件可以去＂玩机广场＂求助葫芦丝\n\nⅡ求游戏，影视资源可以去＂许愿＂板块噢\n\n\n⑦其他问题在本帖留言，一一为大家解决\n\n\n————————————————————\n————————————————————\n\n\n⒊如有个人或者团队自我开发的资源最好加上有明显的能证明是自己原创的因素\n\n①如标题前缀：【原创开发】或个人社区用户名\n\n②此举可能会增加曝光率以及相关奖励首页推荐等相关设置。\n\n（对于简单封装调用别人接口的程序源码并不算原创，禁止前缀带【原创开发】、禁止发布至原创工具区:  修改版权、拿他人源代码进行篡改的伪原创作品的行为我们绝不承认...）\n\n\n————————————————————\n————————————————————\n\n\nPs：对于符合的资源主题，版主以及社区用户可能会给予适当的“葫芦”奖励、社区首页轮播推荐、版块置顶最少3天、同时，希望各位“葫芦侠”大侠 重复的资源软件尽量不要重复发布~\n\n\n————————————————————\n————————————————————\n\n\n⒋【关于完善主题带有“破解”的字词通知】\n\n本版即２０２１年６月１１日起禁止所有分享资源用户主题内出现{破解}{PJ}敏感字词： \n\n可使用{优化}{绿化}{净化}{简化} 相关字词代替   图片上也禁止出现上述两个字词~\n\n[本通知日期前的主题均不受此影响]\n\n\n————————————————————\n————————————————————\n\n\n⒌【关于主题标题及帖子内容里的字词通知】\n\n本版即２０２１年７月１６日起版块内主题、标题及内容禁止出现以下字眼/词句：\n\n翻墙、18禁、、深夜、激情、P站、2毒、外网、v批恩，以及一切带有性暗示、诱惑性、擦边字词  \n\n[于本通知日期前发布的主题，标题，内容版主们均会做出修改优化]\n\n\n————————————————————\n————————————————————\n\n\n⒍网盘密码通知：\n\n从2021.4.4开始\n网盘密码 不能设置 中文密码\n网盘密码 不能设置 中文密码\n网盘密码 不能设置 中文密码\n\n严重影响用户体验，如果不听的锁帖处理哦\n\nPS：四月份之前发布的主题不受影响\n\n\n————————————————————\n————————————————————\n\n\n⒎【关于资源下载网盘的强调说明】\n\n禁止发布任何需强制注册才能下载、访问次数有限制、域名经常更换推广、非会员无法完成某正常操作、达到某正常值则限速或收费等未上市/不知名的私人网盘链接;\n\n其中若不限速且下载无需登录且永久有效访问的公司性网盘链接可以正常发布，但个人搭建的网盘一律禁止。\n\n 推荐:百度网盘、蓝奏网盘、天翼云网盘、微云网盘、阿里云盘、ONEDRIVER云盘等（持续增加中ing...）\n\n网盘分享用户名称;禁止带有推广性质的用户名、论坛名、网站名称/网址、联系方式、相关业务交易名称、电报群组等...\n</text><image>http://cdn.u1.huluxia.com/g4/M02/C0/95/rBAAdmDCWziAcCanAADUxNzGXcw251.png,720,432</image><text></text><image>http://cdn.u1.huluxia.com/g4/M02/C0/95/rBAAdmDCWzqAXiDgAAAlR1Inz6U406.png,424,120</image><text>\n#【邀请函】社区最热门版块向你发出邀请#\n</text><image>http://cdn.u1.huluxia.com/g4/M01/C0/98/rBAAdmDCX2qAZVcvAAFRwsdwyGY637.jpg,720,300</image><text>\n#【实用软件】违规举报/问题反馈/建议/#\n\n\n\n以上内容解释权归属【实用软件】所有，\n     并保留随时更新此内容的权利。</text>',
					images: [],
					score: 0,
					scoreTxt: '',
					hit: 21900,
					commentCount: 54,
					notice: 0,
					weight: 1,
					isGood: 0,
					createTime: 1623350075000,
					activeTime: 1624623265000,
					line: 0,
					user: {
						userID: 18113632,
						nick: null,
						avatar: null,
						gender: 0,
						age: 0,
						role: 0,
						experience: 0,
						credits: 0,
						identityTitle: null,
						identityColor: 0,
						level: 0,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4305,
					status: 0,
					praise: 20,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 48115584,
					title: '【邀请函】社区最热门版块向你发出邀请',
					detail:
						'<text></text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrQaAAp2qAAEMyR9XFHo921.jpg,695,754</image><text>➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n小组介绍：你已经任职其它版块，还想赚额外的葫芦？？？\n　　　　      那么，现在你的机会来啦[勉强]\n\n报名要求：目前仅可兼职本版  搬砖组 或  审核组（任选其一）\n\n奖励措施：（1）８００/月     表现优秀者奖励「神器侠客」称谓一个月\n                   （2）兼职审核组除了８００葫芦/月 还有１０００贡献度/月\n\n其它说明：兼职人员佩戴原任职版块称谓，不予软件正式称谓   活动称谓除外\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊</text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrQiAXeaLAAENV0v0XaY934.jpg,673,731</image><text>➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n小组介绍：\n该小组成员活动任务为 从互联网获取优质无违规的软件，然后分享到版块即算完成每日任务。\n\n报名要求：（1）擅于发现优质软件，乐于分享软件\n                   （2）３楼等级不低于４级，回复不低于１５０+\n\n奖励措施：（1）搬砖9⑹９００葫芦/月，包工头１２００/月\n　　　　　（2）多发一贴奖励１０葫芦，无上限\n                    （3）热门主题优先加精/认证/社区/版块首页推荐\n\n4、称号升级途径：搬砖的-包工头-三当家-二当家-大当家\n\n【实习期任务标准】\n⑴实习期为三天，每天分享两个软件即算完成任务\n⑵实习期内发布一个软件合集主题即算完成考核任务\n\n\n【通过后任务标准】\n⑴每天分享两个软件即算完成任务\n⑵每周发布一个软件合集主题即算完成周任务\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊</text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrQqAF0omAAERsBEBAIk456.jpg,678,736</image><text>➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n小组介绍：\n该小组成员任务为 汉化、破解、精简、制作软件。 \n\n报名要求：有灵活的头脑，有较为丰富的玩机经验。可以独立制作或修改软件资源。汉化，破解，精简均可。 \n\n奖励措施：６００葫芦/月，每个原创软件都有４０-８０葫芦奖励，多干多得。 \n\n称号升级途径: 汉化先锋-汉化达人-汉化大神-三当家-二当家-大当家 \n\n【实习期任务标准】\n ⑴发布三个原创修改（或一个原创开发）\n ⑵完成任务并通过组长审查后即可上称号 \n\n【通过后任务标准】 \n ⑴每周汉化/破解/精简/去广三个软件资源\n ⑵每周原创制作至少一款软件 \n        ▷（１、２项任选其一即算完成任务）\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊</text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrQyAAe08AAEQE-M2CoQ860.jpg,689,748</image><text>➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n小组介绍：\n该小组成员活动任务为 审核软件版葫芦丝发布的资源贴\n\n报名要求：\n（1）年龄需满１８岁，有属于自己的电脑用户，优先考虑。\n（2）需要手持证件照进行实名认证，签订审核协议（介意者勿扰）\n（3）每天社区在线时间稳定充足\n（4）等级满６级，回复量５００+以上。\n\n\n奖励措施：（1）９００葫芦/月     １０００贡献度/月\n             \n称号升级途径:\n菜鸟小黑-入侵高手-参透专家-黑客掌门-六指黑侠\n\n\n【实习期任务标准】\n（1）实习期三天 实习期间没有审核权限\n（2）每天测试１５个以上资源帖\n（3）实习期满后实名认证后上审核权限及称谓\n\n\n【通过后任务标准】\n（1）按值班时间审核软件版块的帖子，值班时间内不能出现堆积情况\n（2）泳池发布个人审核反馈帖，方便用户咨询帖子审核相关情况\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊</text><text>★☆版块整体奖惩措施\n\n（1）新人奖励【８８葫芦】（需满足七天）\n\n（2）全勤奖励【１００葫芦】（整月没有缺勤）\n\n（3）超额奖励【１０葫芦/帖】无上限（仅限  搬砖组）\n\n（4）月佳奖励【１８８葫芦+背景码】（每个组的月 第一名）\n\n（5）漏签每次-３０葫芦，未完成任务每次-３０葫芦（月末 系统扣除）\n\n（6）超过三次未完成任务人员，重新实习。\n（实习次数超过一次未完成取消活动名额）\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n#【实用软件】各称谓葫芦奖励明细#\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n如有报名问题相关情况反馈可联系QQ：２９０１８０６０４５\n\n【实用软件】【Rain】悟静\n               （请备注三楼昵称及添加原因）</text><text></text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrQ6AL5RxAAB-W-3gSfQ249.jpg,498,344</image><text></text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrRGANIJDAAGiE5MSjWk621.jpg,1920,1080</image><text>➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊\n\n小组介绍：\n小组的内容是从首页寻找软件在板块内发布一个软件分享帖子\n\n报名要求：满足四级即可\n\n称号升级奖励：\n背包客→独行侠→逍遥帝（可以兼 任加入团队，但无称号升级路线）\n\n背包客一个帖子１５葫芦，独行侠一个帖子２０葫芦，逍遥帝一个帖子２５葫芦、另外有热帖奖励１００葫芦（不可灌水）\n\n加入神秘小分队团队请联系QQ：\n（备注三楼名及目的）\n\n报名全职，请联系７４９７０６１０５\n\n报名兼职，请联系２２８０７７３０３９\n\n如发布报名消息后长时间未回复你，请尝试再次发布报名消息，人员较多可能会有遗漏\n\n➚\n﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊﹊</text><image>http://cdn.u1.huluxia.com/g4/M01/9C/D4/rBAAdmCrrRKAHOCtAADajzdUdIg633.jpg,1080,455</image><text></text>',
					images: [],
					score: 13,
					scoreTxt: '',
					hit: 32896,
					commentCount: 381,
					notice: 0,
					weight: 1,
					isGood: 0,
					createTime: 1621864585000,
					activeTime: 1623156506000,
					line: 0,
					user: {
						userID: 18113632,
						nick: null,
						avatar: null,
						gender: 0,
						age: 0,
						role: 0,
						experience: 0,
						credits: 0,
						identityTitle: null,
						identityColor: 0,
						level: 0,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4305,
					status: 0,
					praise: 30,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 46993435,
					title: '【实用软件】热贴奖励及主题加精  申请处',
					detail:
						'<text>●热帖奖励明细\n\n一律由版主奖励36葫芦  寓意：3楼\n\n●热帖奖励要求\n\n1、楼层达到200楼。发帖时间不超过四天，过期不候噢[哈哈][玫瑰]\n\n2、软件满足广大葫芦丝的需求，受到葫芦丝喜爱。\n\n3、发帖格式正确，排版美观，软件无违规内容，无引流后台。\n可参考以下两帖子要求\n\n#〖版块版规〗发帖/删帖/禁言/加精标准#\n\n#【实用软件】违规举报/问题反馈/建议/#\n\n4、及时回复别人的提问。\n\n5、不得水回复，禁止使用机器人自动回复，禁止闲聊凑楼层及顶楼。\n\n6、帖子中禁止使用诱导性语言诱导他人回复或刷楼，如下图所示。</text><text>\n●精贴奖励明细\n\n先发放热帖奖励36葫芦，再由版主@小鸽子 奖励100葫芦并加精，优先推送首页轮播。\n\n●申精奖励要求\n\n1、帖子需要先满足热帖要求才能申精。\n\n2、浏览量达到1w。\n\n原创帖 首发优先加精，回复量达到300 \n\n合集帖 软件数5+，回复量达到400。\n\n搬砖帖 质量优，回复量达到400。\n\n3、发帖时间不超过七天，过期不候[玫瑰]\n\n4、特别优秀的帖子可以跳过1-3条规定。\n\n5、已有的软件不重复加精。\n\nPS：\n\n1、特别优秀指 比如 全网原创首发的优质软件，难度大应用广的破解软件。不限于此。\n\n1、若软件后续出现违规内容，将扣除所有奖励并按照版规锁定相关账号。\n\n2、参与本版块活动的人员，可同时领取原有的发帖奖励和热帖精贴奖励。\n\n【若有版规变动会及时更新本帖，请遵照最新的版块要求】\n\n【最后编辑于2020/06/01】\n</text>',
					images: [],
					score: 14,
					scoreTxt: '',
					hit: 66230,
					commentCount: 254,
					notice: 0,
					weight: 1,
					isGood: 0,
					createTime: 1610717013000,
					activeTime: 1611969810000,
					line: 0,
					user: {
						userID: 426562,
						nick: null,
						avatar: null,
						gender: 0,
						age: 0,
						role: 0,
						experience: 0,
						credits: 0,
						identityTitle: null,
						identityColor: 0,
						level: 0,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4305,
					status: 0,
					praise: 42,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				},
				{
					postID: 32035356,
					title: '【实用软件】违规举报/问题反馈/建议/',
					detail:
						'<text>\n\n申精指路☞#【实用软件】热贴奖励及申请 帖子加精 申请处#\n\n（点击蓝色链接即可跳转）　　\n　　　　　　\n　　　　\n</text><image>http://cdn.u1.huluxia.com/g3/M01/23/2E/wKgBOV4-xx2AVxWPAAFv23uWbQY990.png,720,404</image><text>\n\n\n葫芦侠【实用软件】致力于分享优秀、实用等类型资源，受到多数用户反馈一致好评如潮的资源分享版块！\n\n坚绝杜绝“垃圾”“流氓”纯粹性的引流、色情、推广、锁机软件主题出现在本版！\n\n\n致力为喜欢【葫芦侠__实用软件】的用户推送最潮最好的实用软件[玫瑰]\n\n\n</text><image>http://cdn.u1.huluxia.com/g3/M03/3D/D8/wKgBOV1K9MCARyszAAAWJSBLvT4142.jpg,640,80</image><text>\n</text><text>　             ★★★ 【完整内容】★★★\n　　　　　　　\n即日起，若在本版【实用软件】发布“推广、色情、病毒木马、恶意捆绑软件、流氓软件、盗号钓鱼软件、锁机软件，一律拉进黑名单；\n　　　　　　　\n注：造成他人手机锁机或本版利益和形象受损，将第一时间提交互联网管理部门处理，严厉打击不法分子！\n</text><image>http://cdn.u1.huluxia.com/g3/M01/49/F9/wKgBOV5L-zSADM3uAAAZe7RZU9M765.png,640,64</image><text>\n软件内部禁止添加：\n\n（业务广告、加群福利、老司机资源等敏感字眼以及包括违规资源）\n\n\n—-【关于软件存在QQ群的规定说明】——\n\n在本版分享的资源不能在资源的显眼处或者启动页等软件界面明显的地方推广相关加群以及其它违规内容！\n　　　　　　　　　　　　　　\n例：启动页、软件显眼位置、弹窗（后期弹窗）、\n　　　　　　　\n　　　　    　（相关违规展示图）</text><image>http://cdn.u1.huluxia.com/g3/M00/10/27/wKgBOVuMBgaATCbZAACdnkxQAEU714.png,720,320</image><text>\n　　　　　　　\n———【正确的反馈群姿势方法】———\n　　　　　　　\n正规的软件留有反馈群都是在应用的\n【关于界面、声明界面】\n而不是其它影响软件UI美化的位置！\n　　　　　　　\n其次不能是以后期强制弹窗加群的远程更新进行所谓的加群获取所谓的新版本方式\n（   目前主流推广、引流  形式   ）\n　　　　　　\n在资源显眼处或者加群更新或者加群才能使用的一律视为违规。\n\n\n—【关于正确的留有反馈群的资源说明】—\n\n如你的应用并没有违反上面所说的留群规则，那么也请群主以及相关管理员管理好Q群、切实做好以反馈软件bug等内容改进交流讨论作用！发挥好（软件反馈群）真正用处！\n\n备：若用户反馈/举报  QQ群内聊天过程中或者群公告、群介绍 群文件，进行  线报、推广、收费、发布发表与社区相违背的信息以及违法违规行为！\n\n查实后按照社区现行推广处理实施意见！进行删除主题、锁定主题、封禁社区账号等处理措施...\n\n\n</text><image>http://cdn.u1.huluxia.com/g3/M03/3D/D8/wKgBOV1K9MCAIVPBAAAfFRcpGlk158.jpg,640,64</image><text>——————————————————\n         以下类型资源直接不予通过\n——————————————————\n-禁止发布任意形式的影视相关资源\n\n-手游辅助外挂｛腾讯｝（端游吃鸡、CF辅助）\n\n-禁止磁力搜索类资源\n\n-禁止提供色情等与相关法律法规违背的资源内容发布（视频、广告及其它点播服务）\n\n-视频点播类软件，账号获取器类软件以及各类含打码平台需要支付费用的、淘宝支付图片生成器、支付宝转账生成等交易类欺骗性质生成软件\n\n-各种自动回帖群发软件、刷流量、刷赞、刷人气、刷游戏道具等“作弊作假”类软件！\n\n-禁止翻墙软件以及相关SSR等服务\n\n-禁止发布一切关于葫芦侠社区第三方非法工具\n（注意：使用此类工具存在帐号被盗风险！）\n\n-禁止推广其它与本版冲突以及损害【葫芦侠/葫芦侠3楼】的社区/论坛\n\n-禁止网页打包的影视、动漫、小说相关应用\n（因为这充满不确定性）\n</text><text>\n切勿以身试法、版块发布这些内容的发帖人请注意！你的违法行为可能会为你带来惨痛教训 ！\n\n更多关于版块详情请单击下方链接跳转浏览\n\n（安卓社区用户点击蓝色链接即可跳转）\n\n#〖版块版规〗发帖/删帖/禁言/加精标准#\n</text><text></text><image>http://cdn.u1.huluxia.com/g4/M03/48/3E/rBAAdl7OZeKAXoo3AABdaz2IOqI043.jpg,450,294</image><text>\n　　　　　　　　　　更新声明</text>',
					images: [],
					score: 30,
					scoreTxt: '',
					hit: 823398,
					commentCount: 5675,
					notice: 0,
					weight: 1,
					isGood: 0,
					createTime: 1523837945000,
					activeTime: 1565696783000,
					line: 0,
					user: {
						userID: 426562,
						nick: null,
						avatar: null,
						gender: 0,
						age: 0,
						role: 0,
						experience: 0,
						credits: 0,
						identityTitle: null,
						identityColor: 0,
						level: 0,
						levelColor: 0,
						integral: 0,
						uuid: 0,
						integralNick: null,
						signature: null,
						medalList: null,
						nickColor: null,
						nightNickColor: null
					},
					ext: null,
					category: null,
					tagid: 4305,
					status: 0,
					praise: 790,
					voice: null,
					isAuthention: 0,
					isRich: 1,
					appOrientation: 0,
					isAppPost: 0,
					appVersion: null,
					appSize: 0,
					appSystem: null,
					appLogo: null,
					screenshots: null,
					appIntroduce: null,
					appUrl: null,
					appLanguage: null,
					isGif: 0
				}
			],
			category: {
				categoryID: 43,
				model: 0,
				title: '实用软件',
				icon: 'http://cdn.u1.huluxia.com/g3/M01/A4/BC/wKgBOVyqxNaAMKgoAAAZBkscJg4334.png',
				description: '分享好东西，你就是葫芦侠！',
				postCount: 1958275,
				viewCount: 2446771721,
				postCountFormated: '195万',
				viewCountFormated: '24.4亿',
				isGood: 0,
				isSubscribe: 1,
				hide: 0,
				seq: 1,
				subscribeType: 3,
				forumid: 14,
				cateRule:
					'.                  【  概       述 】\r\n    您在浏览本版块之前需认真阅读（未成年人需在家长陪同下阅读）本协议，若您不接受本协议条款，请您立即终止浏览本网站及终止软件的安装使用。\r\n\r\n\r\n           【凡是内容包含以下信息的将给予严惩】\r\n\r\n1、危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的，损害国家荣誉和利益的\r\n2、地域攻击，破坏民族团结的\r\n3、散布谣言，扰乱社会秩序，破坏社会稳定的\r\n4、散布淫秽、色情、赌博、暴力、恐怖或者教唆犯罪的\r\n5、侮辱或者诽谤他人，侵害他人合法权益的\r\n6、有关危害国家政治类话题的\r\n7、含有国家法律法规禁止的其他内容的\r\n        \r\n                  【 免  责  声  明 】\r\n\r\n    本版块是一个实用/绿色的软件及工具的分享平台，所有内容均为用户分享，本版块不提供内容。\r\n\r\n   【一】用户使用规则\r\n   用户不得利用本服务制作、复制、发布、传播、存储含有违反互联网制定的规定信息；\r\n   发布/传播各种违规违纪违法内容、损害他人利益、损害本社区/本版块利益较为严重情况下，会提交相关管理部门·交由法律制裁！\r\n\r\n   【二】分享须知\r\n   1 本版块的信息均由用户分享而来，本版块无法保证该等信息的准确性、完整性、可用性；\r\n   2 本版块无法判断用户分享的信息是否构成对第三方侵权，若有侵权请第一时间与我方联系解决；\r\n   3 若用户发布任何违法或侵犯第三方合法权益的信息的，由用户自行承担责任；\r\n   4 注册用户若违反本协议的约定的，本网站有权在不通知用户的情况下暂停或终止服务账号的使用；\r\n   5 任何有损他人利益和有损本社区/本版块利益的内容都会被删除，根据情况严重性列入黑名单，同时会对其帐号进行禁言/永久锁定等措施。\r\n\r\n   【三】纠纷解决\r\n    若发生任何有争议的纠纷，用户可通过“意见反馈”版块来表示投诉及维权。\r\n\r\n   【四】黑名单 Black List\r\n    从2017年6月1日起，若在本版块发布“推广、色情、病毒木马、恶意捆绑软件、流氓软件、盗号钓鱼软件、锁机软件，一律拉进黑名单；造成他人或本版块利益和形象受损，将第一时间提交网监管理部门，配合互联网整顿，严厉打击不法份子。\r\n    \r\n              \r\n   【五】更多细节请参考本版块置顶处的总版规。任何版块的版规制定以葫芦侠首页官方条例为执行标准。\r\n\r\n   【六】特殊情况或紧急情况，请用下面的联系方式与我方取得联系。\r\n\r\n\r\n                  【官方交流群】 \r\n\r\n\r\n本版块的官方群指定群主：\r\n（一）Admin胡先生 QQ：97692418\r\n（二）小鸽子     QQ：1622631623\r\n\r\n其他QQ号的群主均为假冒，请立即退群以防受到欺诈损失。\r\n\r\n\r\n请认准本版块的官方QQ群：\r\n交流群1：   275367349\r\n交流群2：   463221543\r\n交流群3：   428373067\r\n交流群4：   460578873\r\n交流群5：   512300338\r\n交流群6：   585880732\r\n总考核群:   531325753\r\n搬砖组考核群：434368605 \r\n原创组考核群：235625589\r\n              \r\n【注】：在3楼任意版块招聘、应聘、上称号、下称号等操作都不会索要您的登录密码，也不会产生任何费用。如果您在期间遇到索要账号密码或者任何付费行为，请果断拒绝，然后截图发给版块负责人员投诉。您绑定的相关QQ的密码或者手机登录的密码请和3楼密码分别设置，防止被盗后祸殃其它账户！\r\n\r\n\r\n社区负责人：清欢\r\n联 系 邮箱：55600951@qq.com\r\n\r\n版块管理人：小鸽子      \r\n联 系 邮箱：lyt168@qq.com（正常情况请联系此邮箱即可）',
				type: '2',
				wap: '',
				appId: 0,
				moderator: [
					{
						userID: 1093916,
						nick: 'Rain〃小鸽子',
						avatar: 'http://cdn.u1.huluxia.com/g4/M02/85/26/rBAAdmCbjrKAG7e4AAEcJBVmVN8524.jpg',
						identityTitle: null,
						leveColor: 0
					},
					{
						userID: 426562,
						nick: '【Rain】东鸽',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/12/D5/rBAAdmDxq5KAT2MjAADFrhidd_I528.png',
						identityTitle: null,
						leveColor: 0
					},
					{
						userID: 18113632,
						nick: '【Rain】悟静',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/0F/1D/rBAAdmDvmtOAJUjGAAC5282bO38012.jpg',
						identityTitle: null,
						leveColor: 0
					},
					{
						userID: 17773067,
						nick: '【Rain】余生',
						avatar: 'http://cdn.u1.huluxia.com/g4/M03/B4/A3/rBAAdmC7NpyAPwx1AADc9aqTJY4263.jpg',
						identityTitle: null,
						leveColor: 0
					},
					{
						userID: 9904404,
						nick: 'Rain〃萌丫吖',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/13/4D/rBAAdmDyMtmASubWAAEQa0fWVNQ487.jpg',
						identityTitle: null,
						leveColor: 0
					},
					{
						userID: 16149625,
						nick: '常乐\u2062',
						avatar: 'http://cdn.u1.huluxia.com/g4/M01/40/57/rBAAdmELgMuADxxYAAANrKUaSfs142.jpg',
						identityTitle: null,
						leveColor: 0
					}
				],
				tags: [
					{
						ID: 0,
						name: '全部'
					},
					{
						ID: 4301,
						name: '绿色软件'
					},
					{
						ID: 4302,
						name: '原创工具'
					},
					{
						ID: 4304,
						name: '影音播放'
					},
					{
						ID: 4303,
						name: '集合贴'
					},
					{
						ID: 4305,
						name: '通告活动'
					}
				],
				isSearch: '0',
				hasChild: 0,
				pid: 0
			},
			more: 1,
			start: '1628250514000',
			status: 1
		};

		console.log(data);
		this.posts = data.posts;
	}
};
</script>

<style scoped>
/* *{
    touch-action: none;
} */

.box {
	position: relative;
	height: 300px;
}

#wrapper {
	position: absolute;
	z-index: 1;
	top: 0;
	bottom: 0;
	left: 0;
	width: 100%;
	overflow: hidden;
}

#scroller {
	position: absolute;
	z-index: 1;
	/*	-webkit-touch-callout:none;*/
	-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
	width: 100%;
	padding: 0;
}
</style>